version: 2

project_name: pacto

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: pacto
    main: ./cmd/pacto
    binary: pacto
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X pacto/internal/app.Version={{.Version}}
  - id: pacto-engine
    main: ./cmd/pacto-engine
    binary: pacto-engine
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X pacto/internal/app.Version={{.Version}}

archives:
  - id: default
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: git
